[35기 2사리빙 현진] CategoryView 작성
wecode-bootcamp-korea/35-1st-2sa-living-backend pull request #7
Opened 2022-07-22 06:18 UTC by hjz1010

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 사용자가 대분류를 클릭하면 대분류에 속하는 모둔 제품의 목록을 표출하는 기능 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. client에서 path parameter로 category_id를 담아서 요청하면
2. 요청받은 category_id에 해당하는 모든 제품을 DB에서 찾아서
3. 각 제품의 id, 썸네일 이미지 URL, brand 이름, 제품 이름 + 색상, 가격 을 반환해준다!

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- get 요청시 request.body에 요청 정보를 담아서 보내는 것이 아니라
- URL을 통해서 category_id 등을 받고 
- 이를 get메소드의 인자로 받아서 데이터 가공에 사용하는 방법을 배웠습니다.
 
<br />

## :: 기타 질문 및 특이 사항

2022-07-25 01:56 UTC, Kang-kyunghun requested changes

2022-07-25 01:56 UTC, Kang-kyunghun commented on products/urls.py
> +    # 127.0.0.1:8000/products?sub_category_id=7
불필요한 주석 삭제

2022-07-25 01:56 UTC, Kang-kyunghun commented on db_uploader.py
> +import csv
gitignore에 추가해 주세요.

2022-07-25 01:56 UTC, Kang-kyunghun commented on products.txt
> +id	category	sub_category	brand_name	furniture_korean_name	furniture_english_name	color_korean_name	color_english_name	price(8)	thumbnail_image_url(9)	main_image_url	detail_image_url	is_new
gitignore에 추가해 주세요.

2022-07-25 01:56 UTC, Kang-kyunghun commented on products/views.py
> +        products = Product.objects.filter(sub_category_id = sub_category_id) or Product.objects.filter(sub_category__category_id = category_id)
filter를 구현하기 위해 Q객체를 조사해 보면 좋을 것 같습니다.

2022-07-25 01:56 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'message': 'INVALID_CATEGORY'}, status=400)
product_list가 빈 list이면 빈 list 그대로 보내셔도 좋을 것 같습니다.

2022-07-25 01:56 UTC, Kang-kyunghun commented on products/views.py
> +from .models import Category, Furniture, ProductImage, SubCategory, Product, Brand, Color
사용하지 않는 class 들은 정리 한 번 해주세요.

2022-07-25 01:56 UTC, Kang-kyunghun commented on products/views.py
> +            })
list comprehension으로 바꿔 보세요.

2022-07-25 01:56 UTC, Kang-kyunghun requested changes

2022-07-25 01:56 UTC, Kang-kyunghun commented on products.txt
> +id	category	sub_category	brand_name	furniture_korean_name	furniture_english_name	color_korean_name	color_english_name	price	thumbnail_image_url	main_image_url	detail_image_url	is_new
gitignore에 추가해 주세요.

2022-07-25 08:52 UTC, hjz1010 commented on db_uploader.py
> +import csv
추가하고 업로드 됐던 파일 삭제했습니다:)

2022-07-25 08:53 UTC, hjz1010 commented on products/views.py
> +            return JsonResponse({'message': 'INVALID_CATEGORY'}, status=400)
수정했습니다!

2022-07-25 08:53 UTC, hjz1010 commented on products/views.py
> +            })
컴프리헨션이 가독성이 훨씬 좋네요😁

2022-07-25 08:53 UTC, hjz1010 commented on products/views.py
> +from .models import Category, Furniture, ProductImage, SubCategory, Product, Brand, Color
다 해두는게 좋은게 아니었군요.. ㅎㅎ

2022-07-25 08:54 UTC, hjz1010 commented on products/views.py
> +        products = Product.objects.filter(sub_category_id = sub_category_id) or Product.objects.filter(sub_category__category_id = category_id)
Q객체를 이용하면서 구현하려던 방향으로 기능이 작동하도록 수정해보았습니다!

2022-07-27 06:38 UTC, Kang-kyunghun requested changes

2022-07-27 06:38 UTC, Kang-kyunghun commented on products/views.py
> +            count = len(Product.objects.filter(product_q))
```suggestion
            count = Product.objects.filter(product_q).count()
```

2022-07-27 07:40 UTC, Kang-kyunghun commented
LGTM

2022-07-27 07:40 UTC, merged